name: Linux Compile

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install cmake ninja-build libbz2-dev
      - name: Build
        run: |
          cmake -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build build-cmake -j
      - name: Create Package
        run: |
          mkdir torch-release
          mv build-cmake/torch torch-release/
          cp "$(ldconfig -p | grep libbz2.so.1.0 | tr ' ' '\n' | grep /| head -n1)" torch-release/
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
          name: torch-linux-x64
          path: torch-release

      # New steps to publish release
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            torch-release/*
          tag_name: v1.0.0  # Replace with your release tag
          release_name: Release v1.0.0  # Replace with your release name
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
